import React from 'react';
import { Box, Typography } from '@mui/material';
import { CustomDashboard } from '../../types/dashboard';
import { Employee } from '../../types/salary';

interface CustomDashboardViewProps {
  dashboard: CustomDashboard;
  data: Employee[];
}

const CustomDashboardView: React.FC<CustomDashboardViewProps> = ({
  dashboard,
  data,
}) => {
  return (
    <Box>
      <Typography variant="h4" gutterBottom>
        {dashboard.name}
      </Typography>
      <Typography variant="body1" color="text.secondary" paragraph>
        {dashboard.description}
      </Typography>
      {/* TODO: Implement dynamic dashboard components based on dashboard.components */}
      <Box sx={{ mt: 2 }}>
        <Typography variant="body2" color="text.secondary">
          Generated by AI on {new Date(dashboard.createdAt).toLocaleDateString()}
        </Typography>
      </Box>
    </Box>
  );
};

export default CustomDashboardView; 